### ISSUE TITLE
Babel killed me   ;-)

### ISSUE THREAD

**Issue by slesolliec** [CryptoverseRocks/token-test-suite#1]
This test suite looks really nice indeed.

Too bad I'm too dumb to make Babel / Webpack work with Truffle.

As I'm slowly learning Solidity and I'm a noob with Truffle, I cannot yet figure out how to hack Truffle with the Webpack / Babel black magic, even following some random answers on stackexchange.

Thank you for sharing that suite, but it's surely  something for people more clever than me.

**Comment by mancze** [comment]
Oh, hello! I'm glad somebody actually thinks this package might come handy. Welcome.

As you can see from the sources you came to the very early stage of this package. I basically just extracted the tests we got, encapsulated them as a module and published them with as little effort as possible. I did not want to invest too much time into something no one would use. 

But here you are. I will try to guide you to fix your problem and possibly improve this package. Yet I need to know more details with what is wrong and what were the hiccups. 

Perhaps [this commit](https://github.com/mancze/zeppelin-solidity/commit/4086faec545acf7ea862fcbbf5eb46e77edba786) will come handy. It integrates this test suite into [zeppelin-solidity](https://github.com/OpenZeppelin/zeppelin-solidity/) framework. Especially notice the changes in `truffle-config.js`. It tells babel not to skip this package.

**Comment by ciarmoli-marco** [comment]
@mancze I have the same 'import' issue. When i launch the test i get `Unexpected token 'import'`. I tried to add the changes in `truffle-config.js` as you suggested, but still doesn't work

**Comment by mancze** [comment]
It should be working now. Babel is no longer required and import statements are transpiled at the shipped code.
