### ISSUE TITLE
import no longer works

### ISSUE THREAD

**Issue by SergeySagan** [CryptoverseRocks/token-test-suite#2]
The `import` statement at the top of `suite.js` is no longer working in the latest setup, I had to copy/paste the dependencies into `suite.js`  as a work around...

**Comment by mancze** [comment]
I'm not sure what do you mean by that `import` does not work? Isn't the problem same as in #1?

**Comment by mancze** [comment]
I think I have found the cause. The code in [npm-package](https://github.com/CryptoverseRocks/token-test-suite/tree/npm-package) should work with `require` properly. Also when you would run `npm run build` you should get ES5 compliant code in the `/lib` directory (no babel needed afterwards). I'm working on the npm package.

**Comment by mancze** [comment]
Just updated the branch. In addition the package is now available as a `npm` module: https://www.npmjs.com/package/token-test-suite

Can you test it out please?
