### ISSUE TITLE
ReferenceError: accounts is not defined

### ISSUE THREAD

**Issue by prazek** [CryptoverseRocks/token-test-suite#5]
Hi,

I am not sure how the accounts in the test suite should work - should I define it by myself, or is my setup somehow not complete?

Also, I don't know a lot about npm, but the package requires chai and chai-bignumber to work, so it would be good to have it in documentation :)

**Comment by mancze** [comment]
The `accounts` variable is provided by the truffle so as is `mocha` and `chai`.

I have slightly updated the getting started instructions in 3111583d00ae17cf9b98119bf2e35bb7810ec0db to make it clear from which context the suite should be called.

**Comment by prazek** [comment]
Thanks, I figured it out that I need to get the accounts from the contract function. The updated readme would work great.
